# Basic Site Settings
title: My Awesome Website
author: Your Name
email: your-email@example.com
description: >-
  This is a test site for demonstrating Jekyll with a hamburger menu and Algolia search.

# Theme
theme: minima

# Plugins (we will add more later)
plugins:
  - jekyll-feed
